version: "3.8"

services:

  land-bronze:
    build:
      context: .
      dockerfile: docker/land-bronze.Dockerfile
    user: "1000:1000"
    volumes:
      - /mnt/data/sentinel-pi/src:/mnt/data/sentinel-pi/src
      - /mnt/data/sentinel-pi/data:/mnt/data/sentinel-pi/data
      - /mnt/data/sentinel-pi/logs:/mnt/data/sentinel-pi/logs
    environment:
      - PYTHONPATH=/mnt/data/sentinel-pi
    networks:
      - sentinel-net

  transform-silver:
    build:
      context: .
      dockerfile: docker/transform-silver.Dockerfile
    user: "1000:1000"
    volumes:
      - /mnt/data/sentinel-pi/src:/mnt/data/sentinel-pi/src
      - /mnt/data/sentinel-pi/data:/mnt/data/sentinel-pi/data
      - /mnt/data/sentinel-pi/logs:/mnt/data/sentinel-pi/logs
    environment:
      - PYTHONPATH=/mnt/data/sentinel-pi
    depends_on:
      - land-bronze
    networks:
      - sentinel-net

  transform-gold:
    build:
      context: .
      dockerfile: docker/transform-gold.Dockerfile
    user: "1000:1000"
    volumes:
      - /mnt/data/sentinel-pi/src:/mnt/data/sentinel-pi/src
      - /mnt/data/sentinel-pi/data:/mnt/data/sentinel-pi/data
      - /mnt/data/sentinel-pi/logs:/mnt/data/sentinel-pi/logs
    environment:
      - PYTHONPATH=/mnt/data/sentinel-pi
    depends_on:
      - transform-silver
    networks:
      - sentinel-net

  ai-summary:
    build:
      context: .
      dockerfile: docker/ai-summary.Dockerfile
    user: "1000:1000"
    volumes:
      - /mnt/data/sentinel-pi/src:/app/src
      - /mnt/data/sentinel-pi/data:/app/data
      - /mnt/data/sentinel-pi/logs:/app/logs
      - /mnt/data/sentinel-pi/docs:/app/docs
    environment:
      - PYTHONPATH=/app
      - OLLAMA_URL=http://host.docker.internal:11434/api/generate
    depends_on:
      - transform-gold
    networks:
      - sentinel-net


networks:
  sentinel-net:
    driver: bridge
